<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SystemSetting;

class SystemSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // システム基本設定
            [
                'category' => 'system',
                'key' => 'maintenance_mode',
                'value' => 'false',
                'type' => 'boolean',
                'description' => 'メンテナンスモードの有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'system',
                'key' => 'system_name',
                'value' => 'IT言語別スキル取得講習システム',
                'type' => 'string',
                'description' => 'システム名',
                'is_public' => true,
                'is_editable' => true,
            ],
            [
                'category' => 'system',
                'key' => 'system_version',
                'value' => '2.0.0',
                'type' => 'string',
                'description' => 'システムバージョン',
                'is_public' => false,
                'is_editable' => false,
            ],
            [
                'category' => 'system',
                'key' => 'timezone',
                'value' => 'Asia/Tokyo',
                'type' => 'string',
                'description' => 'デフォルトタイムゾーン',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'system',
                'key' => 'date_switch_time',
                'value' => '07:55',
                'type' => 'string',
                'description' => '日付切り替え時刻',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'system',
                'key' => 'default_language',
                'value' => 'ja',
                'type' => 'string',
                'description' => 'デフォルト言語',
                'is_public' => false,
                'is_editable' => true,
            ],

            // Slack連携設定
            [
                'category' => 'slack',
                'key' => 'enabled',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Slack連携の有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'slack',
                'key' => 'workspace_url',
                'value' => '',
                'type' => 'string',
                'description' => 'SlackワークスペースURL',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'slack',
                'key' => 'bot_token',
                'value' => '',
                'type' => 'string',
                'description' => 'Slack Bot Token',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'slack',
                'key' => 'channel_prefix',
                'value' => 'training-',
                'type' => 'string',
                'description' => 'チャンネル名プレフィックス',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'slack',
                'key' => 'channel_creation_time',
                'value' => '23:00',
                'type' => 'string',
                'description' => 'チャンネル作成時刻',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'slack',
                'key' => 'auto_invite',
                'value' => 'true',
                'type' => 'boolean',
                'description' => '自動招待の有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],

            // 出席設定
            [
                'category' => 'attendance',
                'key' => 'allow_future_days',
                'value' => '1',
                'type' => 'integer',
                'description' => '未来の出席登録可能日数',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'attendance',
                'key' => 'check_in_start_time',
                'value' => '08:00',
                'type' => 'string',
                'description' => 'チェックイン開始時刻',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'attendance',
                'key' => 'check_in_end_time',
                'value' => '10:00',
                'type' => 'string',
                'description' => 'チェックイン終了時刻',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'attendance',
                'key' => 'absent_warning_days',
                'value' => '14',
                'type' => 'integer',
                'description' => '欠席警告日数',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'attendance',
                'key' => 'auto_absent_marking',
                'value' => 'true',
                'type' => 'boolean',
                'description' => '自動欠席マーキング',
                'is_public' => false,
                'is_editable' => true,
            ],

            // ファイルアップロード設定
            [
                'category' => 'file',
                'key' => 'max_upload_size',
                'value' => '104857600', // 100MB
                'type' => 'integer',
                'description' => '最大アップロードサイズ（バイト）',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'file',
                'key' => 'allowed_extensions',
                'value' => json_encode(['zip', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'md', 'jpg', 'png']),
                'type' => 'json',
                'description' => '許可するファイル拡張子',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'file',
                'key' => 'virus_scan_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'ウイルススキャンの有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'file',
                'key' => 'encryption_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'ファイル暗号化の有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'file',
                'key' => 'version_control_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'バージョン管理の有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'file',
                'key' => 'cdn_enabled',
                'value' => 'false',
                'type' => 'boolean',
                'description' => 'CDN配信の有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'file',
                'key' => 'storage_limit',
                'value' => '1073741824000', // 1TB
                'type' => 'integer',
                'description' => 'ストレージ制限（バイト）',
                'is_public' => false,
                'is_editable' => true,
            ],

            // 通知設定
            [
                'category' => 'notification',
                'key' => 'email_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'メール通知の有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'notification',
                'key' => 'slack_notification_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Slack通知の有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'notification',
                'key' => 'push_notification_enabled',
                'value' => 'false',
                'type' => 'boolean',
                'description' => 'プッシュ通知の有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'notification',
                'key' => 'batch_size',
                'value' => '100',
                'type' => 'integer',
                'description' => '通知バッチサイズ',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'notification',
                'key' => 'retry_count',
                'value' => '3',
                'type' => 'integer',
                'description' => '通知リトライ回数',
                'is_public' => false,
                'is_editable' => true,
            ],

            // セキュリティ設定
            [
                'category' => 'security',
                'key' => 'password_min_length',
                'value' => '8',
                'type' => 'integer',
                'description' => 'パスワード最小文字数',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'security',
                'key' => 'password_require_uppercase',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'パスワードに大文字を必須とする',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'security',
                'key' => 'password_require_numbers',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'パスワードに数字を必須とする',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'security',
                'key' => 'password_require_symbols',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'パスワードに記号を必須とする',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'security',
                'key' => 'session_lifetime',
                'value' => '120',
                'type' => 'integer',
                'description' => 'セッション有効時間（分）',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'security',
                'key' => 'max_login_attempts',
                'value' => '5',
                'type' => 'integer',
                'description' => '最大ログイン試行回数',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'security',
                'key' => 'lockout_duration',
                'value' => '30',
                'type' => 'integer',
                'description' => 'アカウントロック時間（分）',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'security',
                'key' => 'allow_multiple_sessions',
                'value' => 'false',
                'type' => 'boolean',
                'description' => '複数セッションを許可',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'security',
                'key' => 'two_factor_enabled',
                'value' => 'false',
                'type' => 'boolean',
                'description' => '2要素認証の有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],

            // API設定
            [
                'category' => 'api',
                'key' => 'rate_limit_per_minute',
                'value' => '60',
                'type' => 'integer',
                'description' => '1分あたりのAPIリクエスト制限',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'api',
                'key' => 'rate_limit_per_hour',
                'value' => '1000',
                'type' => 'integer',
                'description' => '1時間あたりのAPIリクエスト制限',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'api',
                'key' => 'api_logging_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'APIログ記録の有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],

            // レポート設定
            [
                'category' => 'report',
                'key' => 'weekly_report_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'description' => '週次レポートの有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'report',
                'key' => 'monthly_report_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'description' => '月次レポートの有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'report',
                'key' => 'report_send_day',
                'value' => '1',
                'type' => 'integer',
                'description' => 'レポート送信日（1:月曜日）',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'report',
                'key' => 'report_send_time',
                'value' => '09:00',
                'type' => 'string',
                'description' => 'レポート送信時刻',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'report',
                'key' => 'report_format',
                'value' => 'pdf',
                'type' => 'string',
                'description' => 'デフォルトレポート形式',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'report',
                'key' => 'report_retention_days',
                'value' => '90',
                'type' => 'integer',
                'description' => 'レポート保持期間（日）',
                'is_public' => false,
                'is_editable' => true,
            ],

            // 分析設定
            [
                'category' => 'analytics',
                'key' => 'enabled',
                'value' => 'true',
                'type' => 'boolean',
                'description' => '分析機能の有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'analytics',
                'key' => 'data_retention_days',
                'value' => '365',
                'type' => 'integer',
                'description' => '分析データ保持期間（日）',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'analytics',
                'key' => 'prediction_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'description' => '予測機能の有効/無効',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'analytics',
                'key' => 'risk_threshold_attendance',
                'value' => '14',
                'type' => 'integer',
                'description' => '出席リスク閾値（日）',
                'is_public' => false,
                'is_editable' => true,
            ],
            [
                'category' => 'analytics',
                'key' => 'risk_threshold_progress',
                'value' => '5',
                'type' => 'integer',
                'description' => '進捗リスク閾値（課題数）',
                'is_public' => false,
                'is_editable' => true,
            ],
        ];

        foreach ($settings as $setting) {
            SystemSetting::updateOrCreate(
                [
                    'category' => $setting['category'],
                    'key' => $setting['key'],
                ],
                $setting
            );
        }
    }
}